# Generated by Django 2.1.7 on 2019-02-16 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='fulltext',
        ),
        migrations.AddField(
            model_name='post',
            name='shorttext',
            field=models.TextField(default=212),
            preserve_default=False,
        ),
    ]
