# Generated by Django 2.1.7 on 2019-02-17 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190216_2355'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.CharField(max_length=1024, verbose_name='Страница')),
                ('desc', models.CharField(max_length=1024, verbose_name='Описание страницы')),
                ('name', models.CharField(blank=True, max_length=1024, verbose_name='ИМЯ')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
            },
        ),
    ]
