# Generated by Django 2.1.7 on 2019-02-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AddField(
            model_name='order',
            name='prace',
            field=models.PositiveIntegerField(default=100, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
