# Generated by Django 2.1.7 on 2019-02-26 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190226_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='zstatus',
        ),
        migrations.AddField(
            model_name='order',
            name='zstatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.Status', verbose_name='Статус заявки'),
            preserve_default=False,
        ),
    ]
