# Generated by Django 2.1.7 on 2019-02-26 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20190226_2201'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='sale',
            field=models.BooleanField(default=0, verbose_name='Акционная заявка'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=1024, verbose_name='ИМЯ'),
        ),
    ]
