# Generated by Django 2.1.7 on 2019-02-26 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20190226_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='desc',
            field=models.CharField(blank=True, max_length=1024, verbose_name='Описание страницы'),
        ),
    ]
