# Generated by Django 2.2.4 on 2019-08-18 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20190304_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='artimgurl',
            field=models.CharField(default=4, max_length=200, verbose_name='Адрес картинки'),
            preserve_default=False,
        ),
    ]
