# Generated by Django 2.1.5 on 2019-08-22 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_artimgurl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='artimgurl',
        ),
    ]
